### PR TITLE
autotools -> cmake

### PR DESCRIPTION
**Pull request by pieterdavid**
I had a simple cmake (with ROOT) config lying around, so all this took was a simple copy/paste/replace ;-) . `FindROOT.cmake` comes from what ROOT used to bundle at some point, so there may be copyright/license concerns

### CODE REVIEW

**Comment by blinkseb** [comment]
IIRC Boost is also a dependencies, and it can be a bit tricky to add

**Comment by pieterdavid** [comment]
You were right (a header-only dependency on boost/any.hpp, so actually the system one would still work). I tested in CMSSW_8_0_30 on ingrid, which showed a few more things to add: enforcing C++11 (not default for gcc until recently), and supporting older cmake versions (it's there in the externals, but not configured as a tool with CMSSW, so we pick up the one from slc6 which is 2.8.12.2).

**Comment by pieterdavid** [comment]
ping... no pressure, just looking through my list of open PRs ;-) . I think I addressed all comments, but there may be new ones.

**Comment by blinkseb** [comment]
Sorry, I thought I merged this already :) Thanks a lot!

**Pull request merged**
